<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SMWHubASMCodeLibrary\SMWHubASMCodeLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="_Internal\Templates\CodePointersPatchTemplate.asm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="_Internal\Templates\SingleCodePatchTemplate.asm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
