<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0.223</AssemblyVersion>
    <FileVersion>1.0.0.223</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OneOf" Version="3.0.271" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Configs\Configs.csproj" />
    <ProjectReference Include="..\FormatLibrary\FormatLibrary.csproj" />
    <ProjectReference Include="..\LogRegister\LogRegister.csproj" />
    <ProjectReference Include="..\ResourceManagement\ResourceManagement.csproj" />
    <ProjectReference Include="..\SMWHubEnumerators\SMWHubEnumerators.csproj" />
    <ProjectReference Include="..\SMWHubLogging\SMWHubLogging.csproj" />
    <ProjectReference Include="..\SMWHubValidations\SMWHubValidations.csproj" />
    <ProjectReference Include="..\Validations\Validations.csproj" />
    <ProjectReference Include="..\ZWXStateMachine\ZWXStateMachine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Readers\ParsingContexts\StateMachines\" />
    <Folder Include="Readers\ParsingContexts\StateMachines\StateLogics\" />
  </ItemGroup>

</Project>
