<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ASMCodeUtils\ASMCodeUtils.csproj" />
    <ProjectReference Include="..\LogRegister\LogRegister.csproj" />
    <ProjectReference Include="..\Validations\Validations.csproj" />
  </ItemGroup>

</Project>
