<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0.18</AssemblyVersion>
    <FileVersion>1.0.0.18</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FormatLibrary\FormatLibrary.csproj" />
    <ProjectReference Include="..\FormatReadLibrary\FormatReadLibrary.csproj" />
    <ProjectReference Include="..\SMWHubValidations\SMWHubValidations.csproj" />
    <ProjectReference Include="..\Validations\Validations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="_Internal\Settings\FoldersConfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
