<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyVersion>1.0.0.62</AssemblyVersion>
    <FileVersion>1.0.0.62</FileVersion>

    <PackageId>LogRegisterZWX.Logging</PackageId>
    <Version>1.0.0</Version>
    <Authors>anonimzwx</Authors>
    <Description>Flexible logging library that can be adapted to any project.</Description>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
