<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0.23</AssemblyVersion>
    <FileVersion>1.0.0.23</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogRegister\LogRegister.csproj" />
    <ProjectReference Include="..\SMWHubEnumerators\SMWHubEnumerators.csproj" />
    <ProjectReference Include="..\SMWHubValidations\SMWHubValidations.csproj" />
    <ProjectReference Include="..\Validations\Validations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Logging\LogMessages.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
